preset: psr2

enabled:
  - blankline_after_open_tag
  - concat_with_spaces
  - join_function
  - native_function_casing
  - no_blank_lines_after_class_opening
  - ordered_use
  - phpdoc_no_access
  - remove_leading_slash_use
  - self_accessor
  - short_array_syntax
  - spaces_cast
  - unused_use
  - whitespacy_lines

finder:
  exclude:
    - "tests"
  name:
    - "*.php"
    - "*.php.dist"
  path:
    - "."
  not-path:
    - "resources/templates"