<?php

namespace mageekguy\atoum\tests\units\report\fields\runner\errors;

use
	\mageekguy\atoum,
	\mageekguy\atoum\mock,
	\mageekguy\atoum\report,
	\mageekguy\atoum\report\fields\runner
;

require_once(__DIR__ . '/../../../../../runner.php');

class string extends \mageekguy\atoum\tests\units\report\fields\runner\errors
{
	public function testClassConstants()
	{
		$this->assert
			->string(runner\errors\string::titlePrompt)->isEqualTo('> ')
			->string(runner\errors\string::methodPrompt)->isEqualTo('=> ')
			->string(runner\errors\string::errorPrompt)->isEqualTo('==> ')
		;
	}

	public function test__construct()
	{
		$errors = new runner\errors\string();

		$this->assert
			->object($errors)->isInstanceOf('\mageekguy\atoum\report\fields\runner')
			->variable($errors->getRunner())->isNull()
			->object($errors->getLocale())->isInstanceOf('\mageekguy\atoum\locale')
		;
	}

	public function testSetWithRunner()
	{
		$errors = new runner\errors\string();

		$mockGenerator = new mock\generator();
		$mockGenerator->generate('\mageekguy\atoum\runner');

		$runner = new mock\mageekguy\atoum\runner();

		$this->assert
			->object($errors->setWithRunner($runner))->isIdenticalTo($errors)
			->object($errors->getRunner())->isIdenticalTo($runner)
			->object($errors->setWithRunner($runner, atoum\runner::runStart))->isIdenticalTo($errors)
			->object($errors->getRunner())->isIdenticalTo($runner)
			->object($errors->setWithRunner($runner, atoum\runner::runStop))->isIdenticalTo($errors)
			->object($errors->getRunner())->isIdenticalTo($runner)
		;
	}

	public function test__toString()
	{
		$mockGenerator = new mock\generator();
		$mockGenerator
			->generate('\mageekguy\atoum\score')
			->generate('\mageekguy\atoum\runner')
		;

		$score = new mock\mageekguy\atoum\score();

		$runner = new mock\mageekguy\atoum\runner();
		$runner->getMockController()->getScore = function() use ($score) { return $score; };

		$errors = new runner\errors\string($locale = new atoum\locale());

		$this->setCase('There is no error in score');

		$score->getMockController()->getErrors = function() { return array(); };

		$this->assert
			->castToString($errors)->isEmpty()
			->castToString($errors->setWithRunner($runner))->isEmpty()
			->castToString($errors->setWithRunner($runner, atoum\runner::runStart))->isEmpty()
			->castToString($errors->setWithRunner($runner, atoum\runner::runStop))->isEmpty()
		;

		$this->setCase('There is errors with file, line and no case in score');

		$allErrors = array(
			array(
				'case' => null,
				'class' => $class = uniqid(),
				'method' => $method = uniqid(),
				'file' => $file = uniqid(),
				'line' => $line = rand(1, PHP_INT_MAX),
				'type' => $type = uniqid(),
				'message' => $message = uniqid(),
				'errorFile' => $errorFile = uniqid(),
				'errorLine' => $errorLine = rand(1, PHP_INT_MAX),
			),
			array(
				'case' => null,
				'class' => $otherClass = uniqid(),
				'method' => $otherMethod = uniqid(),
				'file' => $otherFile = uniqid(),
				'line' => $otherLine = rand(1, PHP_INT_MAX),
				'type' => $otherType = uniqid(),
				'message' => ($firstOtherMessage = uniqid()) . PHP_EOL . ($secondOtherMessage = uniqid()),
				'errorFile' => $otherErrorFile = uniqid(),
				'errorLine' => $otherErrorLine = rand(1, PHP_INT_MAX),
			),
		);

		$score->getMockController()->getErrors = function() use ($allErrors) { return $allErrors; };

		$errors = new runner\errors\string($locale = new atoum\locale());

		$this->assert
			->castToString($errors)->isEmpty()
			->castToString($errors->setWithRunner($runner))->isEqualTo(runner\errors\string::titlePrompt . sprintf($locale->__('There is %d error:', 'There are %d errors:', sizeof($allErrors)), sizeof($allErrors)) . PHP_EOL .
				runner\errors\string::methodPrompt . $class . '::' . $method . '():' . PHP_EOL .
				runner\errors\string::errorPrompt . sprintf($locale->_('Error %s in %s on line %d, generated by file %s on line %d:'), $type, $file, $line, $errorFile, $errorLine) . PHP_EOL .
				$message . PHP_EOL .
				runner\errors\string::methodPrompt . $otherClass . '::' . $otherMethod . '():' . PHP_EOL .
				runner\errors\string::errorPrompt . sprintf($locale->_('Error %s in %s on line %d, generated by file %s on line %d:'), $otherType, $otherFile, $otherLine, $otherErrorFile, $otherErrorLine) . PHP_EOL .
				$firstOtherMessage . PHP_EOL .
				$secondOtherMessage . PHP_EOL
			)
		;

		$this->setCase('There is errors with file, line and case in score');

		$allErrors = array(
			array(
				'case' => $case = uniqid(),
				'class' => $class = uniqid(),
				'method' => $method = uniqid(),
				'file' => $file = uniqid(),
				'line' => $line = rand(1, PHP_INT_MAX),
				'type' => $type = uniqid(),
				'message' => $message = uniqid(),
				'errorFile' => $errorFile = uniqid(),
				'errorLine' => $errorLine = rand(1, PHP_INT_MAX),
			),
			array(
				'case' => $otherCase = uniqid(),
				'class' => $otherClass = uniqid(),
				'method' => $otherMethod = uniqid(),
				'file' => $otherFile = uniqid(),
				'line' => $otherLine = rand(1, PHP_INT_MAX),
				'type' => $otherType = uniqid(),
				'message' => ($firstOtherMessage = uniqid()) . PHP_EOL . ($secondOtherMessage = uniqid()),
				'errorFile' => $otherErrorFile = uniqid(),
				'errorLine' => $otherErrorLine = rand(1, PHP_INT_MAX),
			),
		);

		$score->getMockController()->getErrors = function() use ($allErrors) { return $allErrors; };

		$errors = new runner\errors\string($locale = new atoum\locale());

		$this->assert
			->castToString($errors)->isEmpty()
			->castToString($errors->setWithRunner($runner))->isEqualTo(runner\errors\string::titlePrompt . sprintf($locale->__('There is %d error:', 'There are %d errors:', sizeof($allErrors)), sizeof($allErrors)) . PHP_EOL .
				runner\errors\string::methodPrompt . $class . '::' . $method . '():' . PHP_EOL .
				runner\errors\string::errorPrompt . sprintf($locale->_('Error %s in %s on line %d, generated by file %s on line %d in case \'%s\':'), $type, $file, $line, $errorFile, $errorLine, $case) . PHP_EOL .
				$message . PHP_EOL .
				runner\errors\string::methodPrompt . $otherClass . '::' . $otherMethod . '():' . PHP_EOL .
				runner\errors\string::errorPrompt . sprintf($locale->_('Error %s in %s on line %d, generated by file %s on line %d in case \'%s\':'), $otherType, $otherFile, $otherLine, $otherErrorFile, $otherErrorLine, $otherCase) . PHP_EOL .
				$firstOtherMessage . PHP_EOL .
				$secondOtherMessage . PHP_EOL
			)
		;

		$this->setCase('There is errors with no file, no line and no case in score');

		$allErrors = array(
			array(
				'case' => null,
				'class' => $class = uniqid(),
				'method' => $method = uniqid(),
				'file' => null,
				'line' => null,
				'type' => $type = uniqid(),
				'message' => $message = uniqid(),
				'errorFile' => $errorFile = uniqid(),
				'errorLine' => $errorLine = rand(1, PHP_INT_MAX),
			)
		);

		$score->getMockController()->getErrors = function() use ($allErrors) { return $allErrors; };

		$errors = new runner\errors\string($locale = new atoum\locale());

		$this->assert
			->castToString($errors)->isEmpty()
			->castToString($errors->setWithRunner($runner))->isEqualTo(runner\errors\string::titlePrompt . sprintf($locale->__('There is %d error:', 'There are %d errors:', sizeof($allErrors)), sizeof($allErrors)) . PHP_EOL .
				runner\errors\string::methodPrompt . $class . '::' . $method . '():' . PHP_EOL .
				runner\errors\string::errorPrompt . sprintf($locale->_('Error %s in unknown file on unknown line, generated by file %s on line %d:'), $type, $errorFile, $errorLine) . PHP_EOL .
				$message . PHP_EOL
			)
		;

		$this->setCase('There is errors with no file, no line and case in score');

		$allErrors = array(
			array(
				'case' => $case = uniqid(),
				'class' => $class = uniqid(),
				'method' => $method = uniqid(),
				'file' => null,
				'line' => null,
				'type' => $type = uniqid(),
				'message' => $message = uniqid(),
				'errorFile' => $errorFile = uniqid(),
				'errorLine' => $errorLine = rand(1, PHP_INT_MAX),
			)
		);

		$score->getMockController()->getErrors = function() use ($allErrors) { return $allErrors; };

		$errors = new runner\errors\string($locale = new atoum\locale());

		$this->assert
			->castToString($errors)->isEmpty()
			->castToString($errors->setWithRunner($runner))->isEqualTo(runner\errors\string::titlePrompt . sprintf($locale->__('There is %d error:', 'There are %d errors:', sizeof($allErrors)), sizeof($allErrors)) . PHP_EOL .
				runner\errors\string::methodPrompt . $class . '::' . $method . '():' . PHP_EOL .
				runner\errors\string::errorPrompt . sprintf($locale->_('Error %s in unknown file on unknown line, generated by file %s on line %d in case \'%s\':'), $type, $errorFile, $errorLine, $case) . PHP_EOL .
				$message . PHP_EOL
			)
		;

		$this->setCase('There is errors with no file, line and no case in score');

		$allErrors = array(
			array(
				'case' => null,
				'class' => $class = uniqid(),
				'method' => $method = uniqid(),
				'file' => null,
				'line' => $line = rand(1, PHP_INT_MAX),
				'type' => $type = uniqid(),
				'message' => $message = uniqid(),
				'errorFile' => $errorFile = uniqid(),
				'errorLine' => $errorLine = rand(1, PHP_INT_MAX),
			)
		);

		$score->getMockController()->getErrors = function() use ($allErrors) { return $allErrors; };

		$errors = new runner\errors\string($locale = new atoum\locale());

		$this->assert
			->castToString($errors)->isEmpty()
			->castToString($errors->setWithRunner($runner))->isEqualTo(runner\errors\string::titlePrompt . sprintf($locale->__('There is %d error:', 'There are %d errors:', sizeof($allErrors)), sizeof($allErrors)) . PHP_EOL .
				runner\errors\string::methodPrompt . $class . '::' . $method . '():' . PHP_EOL .
				runner\errors\string::errorPrompt . sprintf($locale->_('Error %s in unknown file on unknown line, generated by file %s on line %d:'), $type, $errorFile, $errorLine) . PHP_EOL .
				$message . PHP_EOL
			)
		;

		$this->setCase('There is errors with no file, line and case in score');

		$allErrors = array(
			array(
				'case' => $case = uniqid(),
				'class' => $class = uniqid(),
				'method' => $method = uniqid(),
				'file' => null,
				'line' => $line = rand(1, PHP_INT_MAX),
				'type' => $type = uniqid(),
				'message' => $message = uniqid(),
				'errorFile' => $errorFile = uniqid(),
				'errorLine' => $errorLine = rand(1, PHP_INT_MAX),
			)
		);

		$score->getMockController()->getErrors = function() use ($allErrors) { return $allErrors; };

		$errors = new runner\errors\string($locale = new atoum\locale());

		$this->assert
			->castToString($errors)->isEmpty()
			->castToString($errors->setWithRunner($runner))->isEqualTo(runner\errors\string::titlePrompt . sprintf($locale->__('There is %d error:', 'There are %d errors:', sizeof($allErrors)), sizeof($allErrors)) . PHP_EOL .
				runner\errors\string::methodPrompt . $class . '::' . $method . '():' . PHP_EOL .
				runner\errors\string::errorPrompt . sprintf($locale->_('Error %s in unknown file on unknown line, generated by file %s on line %d in case \'%s\':'), $type, $errorFile, $errorLine, $case) . PHP_EOL .
				$message . PHP_EOL
			)
		;

		$this->setCase('There is errors with file, no line and no case in score');

		$allErrors = array(
			array(
				'case' => null,
				'class' => $class = uniqid(),
				'method' => $method = uniqid(),
				'file' => $file = uniqid(),
				'line' => null,
				'type' => $type = uniqid(),
				'message' => $message = uniqid(),
				'errorFile' => $errorFile = uniqid(),
				'errorLine' => $errorLine = rand(1, PHP_INT_MAX),
			)
		);

		$score->getMockController()->getErrors = function() use ($allErrors) { return $allErrors; };

		$errors = new runner\errors\string($locale = new atoum\locale());

		$this->assert
			->castToString($errors)->isEmpty()
			->castToString($errors->setWithRunner($runner))->isEqualTo(runner\errors\string::titlePrompt . sprintf($locale->__('There is %d error:', 'There are %d errors:', sizeof($allErrors)), sizeof($allErrors)) . PHP_EOL .
				runner\errors\string::methodPrompt . $class . '::' . $method . '():' . PHP_EOL .
				runner\errors\string::errorPrompt . sprintf($locale->_('Error %s in %s on unknown line, generated by file %s on line %d:'), $type, $file, $errorFile, $errorLine) . PHP_EOL .
				$message . PHP_EOL
			)
		;

		$this->setCase('There is errors with file, no line and case in score');

		$allErrors = array(
			array(
				'case' => $case = uniqid(),
				'class' => $class = uniqid(),
				'method' => $method = uniqid(),
				'file' => $file = uniqid(),
				'line' => null,
				'type' => $type = uniqid(),
				'message' => $message = uniqid(),
				'errorFile' => $errorFile = uniqid(),
				'errorLine' => $errorLine = rand(1, PHP_INT_MAX),
			)
		);

		$score->getMockController()->getErrors = function() use ($allErrors) { return $allErrors; };

		$errors = new runner\errors\string($locale = new atoum\locale());

		$this->assert
			->castToString($errors)->isEmpty()
			->castToString($errors->setWithRunner($runner))->isEqualTo(runner\errors\string::titlePrompt . sprintf($locale->__('There is %d error:', 'There are %d errors:', sizeof($allErrors)), sizeof($allErrors)) . PHP_EOL .
				runner\errors\string::methodPrompt . $class . '::' . $method . '():' . PHP_EOL .
				runner\errors\string::errorPrompt . sprintf($locale->_('Error %s in %s on unknown line, generated by file %s on line %d in case \'%s\':'), $type, $file, $errorFile, $errorLine, $case) . PHP_EOL .
				$message . PHP_EOL
			)
		;
	}
}

?>
