<?php

namespace mageekguy\tests\unit\reporters;

use \mageekguy\tests\unit\test;

class cli extends \mageekguy\tests\unit\reporter
{
	protected $run = 0;
	protected $progressBar = '';
	protected $testMethods = 0;
	protected $testMethodNumber = 0;

	public function manageObservableEvent(\mageekguy\tests\unit\observable $test, $event)
	{
		switch ($event)
		{
			case test::eventRunStart:
				$this->runStart($test);
				break;

			case test::eventBeforeTestMethod:
				$this->testMethods++;
				break;

			case test::eventSuccess:
				$this->progressBar('.');
				break;

			case test::eventFailure:
				$this->progressBar('F');
				break;

			case test::eventError:
			case test::eventException:
				$this->progressBar('!');
				break;

			case test::eventRunEnd:
				$this->runEnd($test);
				break;
		}
	}

	protected function runStart(\mageekguy\tests\unit\test $test)
	{
		if ($this->run == 0)
		{
			self::write(sprintf($this->locale->_('\mageekguy\tests\unit\test version %s by %s.'), $test->getVersion(), \mageekguy\tests\unit\test::author));

			$this->progressBar = '';
			$this->testMethods = 0;
			$this->testMethodNumber = sizeof($test);
		}

		self::write(sprintf($this->locale->_('Run %s...'), $test->getClass()));
		$this->progressBar();

		$this->run++;
	}

	protected function progressBar($dot = '')
	{
		$end = '[' . sprintf('%' . strlen($this->testMethodNumber) . 'd', $this->testMethods) . '/' . $this->testMethodNumber . ']';

		if (strlen($this->progressBar) >= 60)
		{
			self::write();
		}
		else if ($this->testMethods > 0)
		{
			echo str_repeat("\010", 60 + strlen($end));
		}

		$this->progressBar .= $dot;

		echo str_pad(str_pad($this->progressBar, $this->testMethodNumber, '?', STR_PAD_RIGHT), 60, '_', STR_PAD_RIGHT) . $end;
	}

	protected function runEnd(\mageekguy\tests\unit\test $test)
	{
		$score = $test->getScore();

		$failNumber = $score->getFailNumber();
		$errorNumber = $score->getErrorNumber();
		$exceptionNumber = $score->getExceptionNumber();
		$outputNumber = $score->getOutputNumber();
		$duration = $score->getTotalDuration();

		self::write();

		if ($failNumber <= 0)
		{
			if ($errorNumber === 0 && $exceptionNumber === 0)
			{
				self::write(sprintf($this->locale->_('Success ! (%s, %s)'), sprintf($this->locale->__('%d test', '%d tests', $this->testMethodNumber), $this->testMethodNumber), sprintf($this->locale->__('%d assertion', '%d assertions', $score->getAssertionNumber()), $score->getAssertionNumber())));
			}
			else
			{
				self::write($this->locale->_('Success but there are some errors...'));
			}
		}

		self::write(sprintf($this->locale->__('Duration: %4.2f second, Memory %4.2f Mb.', 'Duration: %4.2f seconds, Memory %4.2f Mb', $duration), $duration, memory_get_peak_usage(true) / 1048576));

		if ($outputNumber > 0)
		{
			self::write($this->locale->_('Output:'));

			foreach ($score->getOutputs() as $output)
			{
				self::write($output['class'] . '::' . $output['method'] . '():', 1);

				foreach (explode("\n", trim($output['output'])) as $line)
				{
					self::write($line, 2);
				}
			}
		}

		if ($failNumber > 0)
		{
			self::write(sprintf($this->locale->__('There was %d failure', 'There were %d failures', $failNumber), $failNumber) . ':');

			foreach ($score->getFailAssertions() as $assertion)
			{
				self::write($assertion['class'] . '::' . $assertion['method'] . '():', 1);
				self::write(sprintf('%s failed because %s in file %s at line %d', $assertion['asserter'], $assertion['fail'], $assertion['file'], $assertion['line']), 2);
			}
		}

		if ($errorNumber > 0)
		{
			self::write(sprintf($this->locale->__('There was %d error', 'There were %d errors', $errorNumber), $errorNumber) . ':');

			foreach ($score->getErrors() as $error)
			{
				self::write($error['class'] . '::' . $error['method'] . '():', 1);
				self::write(sprintf($this->locale->_('Error %s with message \'%s\' generated by file %s at line %d'), self::getErrorLabel($error['type']), $error['message'], $error['file'], $error['line']), 2);
			}
		}

		if ($exceptionNumber > 0)
		{
			self::write(sprintf($this->locale->__('There was %d exception', 'There were %d exceptions', $exceptionNumber), $exceptionNumber) . ':');

			foreach ($score->getExceptions() as $exception)
			{
				self::write($exception['class'] . '::' . $exception['method'] . '():', 1);
				self::write(sprintf($this->locale->_('Exception %s with message \'%s\' generated by file %s at line %d'), get_class($exception['exception']), $exception['exception']->getMessage(), $exception['file'], $exception['line']), 2);
			}
		}

		return $this;
	}

	public static function write($message = '', $level = 0)
	{
		if ($message != '')
		{
			echo ($level <= 0 ? '' : str_repeat('   ', $level)) . ltrim($message);
		}

		echo PHP_EOL;
	}
}

?>
