<?php

namespace mageekguy\atoum\tests\units\php;

use
	\mageekguy\atoum,
	\mageekguy\atoum\php
;

require_once(__DIR__ . '/../../runner.php');

class tokenizer extends atoum\test
{
	public function testClass()
	{
		$this->assert
			->testedClass->hasInterface('\IteratorAggregate')
		;
	}

	public function test__construct()
	{
		$tokenizer = new php\tokenizer();

		$this->assert
			->object($iterator = $tokenizer->getIterator())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->sizeOf($iterator)->isZero()
		;
	}

	public function testResetIterator()
	{
		$tokenizer = new php\tokenizer();

		$this->assert
			->object($tokenizer->resetIterator())->isIdenticalTo($tokenizer)
			->sizeOf($tokenizer->getIterator())->isZero()
			->sizeOf($tokenizer->tokenize(uniqid())->getIterator())->isEqualTo(1)
			->object($tokenizer->resetIterator())->isIdenticalTo($tokenizer)
			->sizeOf($tokenizer->getIterator())->isZero()
		;

	}

	public function testTokenize()
	{
		$tokenizer = new php\tokenizer();

		$this->startCase('Tokenizing empty string');

		$this->assert
			->object($tokenizer->tokenize(''))->isIdenticalTo($tokenizer)
			->sizeOf($tokenizer->getIterator())->isZero()
		;

		$this->startCase('Tokenizing a string which is not PHP code');

		$this->assert
			->object($tokenizer->tokenize($value = uniqid()))->isIdenticalTo($tokenizer)
			->sizeOf($iterator = $tokenizer->getIterator())->isEqualTo(1)
			->object($iterator->current())->isEqualTo(new php\tokenizer\token(T_INLINE_HTML, $value, 1, $iterator))
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
		;

		$this->startCase('Tokenizing open and close PHP tags');

		$tokenizer = new php\tokenizer();

		$this->assert
			->object($tokenizer->resetIterator()->tokenize($php = '<?php ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator = $tokenizer->getIterator())->isEqualTo(2)
			->castToString($iterator->current())->isEqualTo('<?php ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castToString($iterator->next()->current())->isEqualTo('?>')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->boolean($iterator->next()->valid())->isFalse()
		;

		$this->startCase('Tokenizing a single namespace without contents');

		$this->assert
			->object($tokenizer->resetIterator()->tokenize($php = '<?php namespace foo; ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator = $tokenizer->getIterator())->isEqualTo(7)
			->castToString($iterator->current())->isEqualTo('<?php ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castToString($iterator->next()->current())->isEqualTo('namespace')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator->getValue())
			->object($namespaceIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($namespaceIterator->getParent())->isIdenticalTo($iterator)
			->castToString($namespaceIterator->current())->isEqualTo('namespace')
			->object($namespaceIterator->current()->getParent())->isIdenticalTo($namespaceIterator)
			->castToString($namespaceIterator->next()->current())->isEqualTo(' ')
			->object($namespaceIterator->current()->getParent())->isIdenticalTo($namespaceIterator)
			->castToString($namespaceIterator->next()->current())->isEqualTo('foo')
			->object($namespaceIterator->current()->getParent())->isIdenticalTo($namespaceIterator)
			->castToString($namespaceIterator->next()->current())->isEqualTo(';')
			->object($namespaceIterator->current()->getParent())->isIdenticalTo($namespaceIterator)
			->castToString($namespaceIterator->next()->current())->isEqualTo(' ')
			->object($namespaceIterator->current()->getParent())->isIdenticalTo($namespaceIterator)
			->boolean($namespaceIterator->next()->valid())->isFalse()
			->castToString($iterator->end()->current())->isEqualTo('?>')
			->boolean($iterator->next()->valid())->isFalse()
		;

		$this->startCase('Tokenizing several namespace without contents');

		$this->assert
			->object($tokenizer->resetIterator()->tokenize($php = '<?php namespace foo; namespace bar; ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator)->isEqualTo(12)
			->object($tokenizer->resetIterator()->tokenize($php = '<?php namespace foo; class bar {} ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator = $tokenizer->getIterator())->isEqualTo(14)
			->castTostring($iterator->current())->isEqualTo('<?php ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('namespace')
			->object($namespaceIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($namespaceIterator->getParent())->isIdenticalTo($iterator)
			->castTostring($namespaceIterator->current())->isEqualTo('namespace')
			->object($namespaceIterator->current()->getParent())->isIdenticalTo($namespaceIterator)
			->castTostring($namespaceIterator->next()->current())->isEqualTo(' ')
			->object($namespaceIterator->current()->getParent())->isIdenticalTo($namespaceIterator)
			->castTostring($namespaceIterator->next()->current())->isEqualTo('foo')
			->object($namespaceIterator->current()->getParent())->isIdenticalTo($namespaceIterator)
			->castTostring($namespaceIterator->next()->current())->isEqualTo(';')
			->object($namespaceIterator->current()->getParent())->isIdenticalTo($namespaceIterator)
			->castTostring($namespaceIterator->next()->current())->isEqualTo(' ')
			->object($namespaceIterator->current()->getParent())->isIdenticalTo($namespaceIterator)
			->castTostring($namespaceIterator->next()->current())->isEqualTo('class')
			->object($classIterator = $namespaceIterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->getParent())->isIdenticalTo($namespaceIterator)
			->castTostring($classIterator->current())->isEqualTo('class')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('bar')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('{')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('}')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->boolean($classIterator->next()->valid())->isFalse()
			->castTostring($namespaceIterator->end()->current())->isEqualTo(' ')
			->object($namespaceIterator->current()->getParent())->isIdenticalTo($namespaceIterator)
			->boolean($namespaceIterator->next()->valid())->isFalse()
			->castTostring($iterator->end()->current())->isEqualTo('?>')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->boolean($iterator->next()->valid())->isFalse()
		;

		$this->startCase('Tokenizing a single class');

		$this->assert
			->object($tokenizer->resetIterator()->tokenize($php = '<?php class foo {} ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator)->isEqualTo(9)
			->castTostring($iterator->current())->isEqualTo('<?php ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('class')
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->getParent())->isIdenticalTo($iterator)
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('foo')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('{')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('}')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->boolean($classIterator->next()->valid())->isFalse()
			->castTostring($iterator->next()->current())->isEqualTo(' ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('?>')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->boolean($iterator->next()->valid())->isFalse()
		;

		$this->startCase('Tokenizing a single abstract class');

		$this->assert
			->object($tokenizer->resetIterator()->tokenize($php = '<?php abstract class foo {} ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator)->isEqualTo(11)
			->castTostring($iterator->current())->isEqualTo('<?php ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('abstract')
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->getParent())->isIdenticalTo($iterator)
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('class')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('foo')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('{')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('}')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->boolean($classIterator->next()->valid())->isFalse()
			->castTostring($iterator->next()->current())->isEqualTo(' ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('?>')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->boolean($iterator->next()->valid())->isFalse()
		;

		$this->startCase('Tokenizing a single final class');

		$this->assert
			->object($tokenizer->resetIterator()->tokenize($php = '<?php final class foo {} ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator)->isEqualTo(11)
			->castTostring($iterator->current())->isEqualTo('<?php ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('final')
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->getParent())->isIdenticalTo($iterator)
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('class')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('foo')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('{')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('}')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->boolean($classIterator->next()->valid())->isFalse()
			->castTostring($iterator->next()->current())->isEqualTo(' ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('?>')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->boolean($iterator->next()->valid())->isFalse()
		;

		$this->startCase('Tokenizing several classes');

		$this->assert
			->object($tokenizer->resetIterator()->tokenize($php = '<?php class foo {} class bar {} ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator)->isEqualTo(16)
			->castTostring($iterator->current())->isEqualTo('<?php ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('class')
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->getParent())->isIdenticalTo($iterator)
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('foo')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('{')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('}')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->boolean($classIterator->next()->valid())->isFalse()
			->castTostring($iterator->next()->current())->isEqualTo(' ')
			->castTostring($iterator->next()->current())->isEqualTo('class')
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('bar')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('{')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('}')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->boolean($classIterator->next()->valid())->isFalse()
			->castTostring($iterator->next()->current())->isEqualTo(' ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('?>')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->boolean($iterator->next()->valid())->isFalse()
		;

		$this->startCase('Tokenizing single class with a single public attribute');

		$this->assert
			->object($tokenizer->resetIterator()->tokenize($php = '<?php class foo { public $bar; } ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator)->isEqualTo(15)
			->castTostring($iterator->current())->isEqualTo('<?php ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('class')
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->getParent())->isIdenticalTo($iterator)
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('foo')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('{')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('public')
			->object($propertyIterator = $classIterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($propertyIterator->getParent())->isIdenticalTo($classIterator)
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->current())->isEqualTo('public')
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->next()->current())->isEqualTo(' ')
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->next()->current())->isEqualTo('$bar')
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->boolean($propertyIterator->next()->valid())->isFalse()
			->castTostring($classIterator->next()->current())->isEqualTo(';')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('}')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->boolean($classIterator->next()->valid())->isFalse()
			->castTostring($iterator->next()->current())->isEqualTo(' ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('?>')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->boolean($iterator->next()->valid())->isFalse()
		;

		$this->startCase('Tokenizing single class with a single protected attribute');

		$this->assert
			->object($tokenizer->resetIterator()->tokenize($php = '<?php class foo { protected $bar; } ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator)->isEqualTo(15)
			->castTostring($iterator->current())->isEqualTo('<?php ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('class')
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->getParent())->isIdenticalTo($iterator)
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('foo')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('{')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('protected')
			->object($propertyIterator = $classIterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($propertyIterator->getParent())->isIdenticalTo($classIterator)
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->current())->isEqualTo('protected')
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->next()->current())->isEqualTo(' ')
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->next()->current())->isEqualTo('$bar')
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->boolean($propertyIterator->next()->valid())->isFalse()
			->castTostring($classIterator->next()->current())->isEqualTo(';')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('}')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->boolean($classIterator->next()->valid())->isFalse()
			->castTostring($iterator->next()->current())->isEqualTo(' ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('?>')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->boolean($iterator->next()->valid())->isFalse()
		;

		$this->startCase('Tokenizing single class with a single private attribute');

		$this->assert
			->object($tokenizer->resetIterator()->tokenize($php = '<?php class foo { private $bar; } ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator)->isEqualTo(15)
			->castTostring($iterator->current())->isEqualTo('<?php ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('class')
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->getParent())->isIdenticalTo($iterator)
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('foo')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('{')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('private')
			->object($propertyIterator = $classIterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($propertyIterator->getParent())->isIdenticalTo($classIterator)
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->current())->isEqualTo('private')
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->next()->current())->isEqualTo(' ')
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->next()->current())->isEqualTo('$bar')
			->boolean($propertyIterator->next()->valid())->isFalse()
			->castTostring($classIterator->next()->current())->isEqualTo(';')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('}')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->boolean($classIterator->next()->valid())->isFalse()
			->castTostring($iterator->next()->current())->isEqualTo(' ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('?>')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->boolean($iterator->next()->valid())->isFalse()
		;

		$this->startCase('Tokenizing single class with several public attributes');

		$this->assert
			->object($tokenizer->resetIterator()->tokenize($php = '<?php class foo { public $bar, $foo; } ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator)->isEqualTo(18)
			->castTostring($iterator->current())->isEqualTo('<?php ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('class')
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->getParent())->isIdenticalTo($iterator)
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('foo')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('{')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('public')
			->object($propertyIterator = $classIterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($propertyIterator->getParent())->isIdenticalTo($classIterator)
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->current())->isEqualTo('public')
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->next()->current())->isEqualTo(' ')
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->next()->current())->isEqualTo('$bar')
			->boolean($propertyIterator->next()->valid())->isFalse()
			->castTostring($classIterator->next()->current())->isEqualTo(',')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('$foo')
			->object($propertyIterator = $classIterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($propertyIterator->getParent())->isIdenticalTo($classIterator)
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->current())->isEqualTo('$foo')
			->boolean($propertyIterator->next()->valid())->isFalse()
			->castTostring($classIterator->next()->current())->isEqualTo(';')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('}')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->boolean($classIterator->next()->valid())->isFalse()
			->castTostring($iterator->next()->current())->isEqualTo(' ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('?>')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->boolean($iterator->next()->valid())->isFalse()
		;

		$this->startCase('Tokenizing single class with several distinct public attributes');

		$this->assert
			->object($tokenizer->resetIterator()->tokenize($php = '<?php class foo { public $bar; public $foo; } ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator)->isEqualTo(20)
			->castTostring($iterator->current())->isEqualTo('<?php ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('class')
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->getParent())->isIdenticalTo($iterator)
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('foo')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('{')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('public')
			->object($propertyIterator = $classIterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($propertyIterator->getParent())->isIdenticalTo($classIterator)
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->current())->isEqualTo('public')
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->next()->current())->isEqualTo(' ')
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->next()->current())->isEqualTo('$bar')
			->boolean($propertyIterator->next()->valid())->isFalse()
			->castTostring($classIterator->next()->current())->isEqualTo(';')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('public')
			->object($propertyIterator = $classIterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($propertyIterator->getParent())->isIdenticalTo($classIterator)
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->current())->isEqualTo('public')
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->next()->current())->isEqualTo(' ')
			->object($propertyIterator->current()->getParent())->isIdenticalTo($propertyIterator)
			->castTostring($propertyIterator->next()->current())->isEqualTo('$foo')
			->boolean($propertyIterator->next()->valid())->isFalse()
			->castTostring($classIterator->next()->current())->isEqualTo(';')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('}')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->boolean($classIterator->next()->valid())->isFalse()
			->castTostring($iterator->next()->current())->isEqualTo(' ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('?>')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->boolean($iterator->next()->valid())->isFalse()
		;

		$this->startCase('Tokenizing single class with single implicit public method');

		$this->assert
			->object($tokenizer->resetIterator()->tokenize($php = '<?php class foo { function bar() {} } ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator)->isEqualTo(19)
			->castTostring($iterator->current())->isEqualTo('<?php ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('class')
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->getParent())->isIdenticalTo($iterator)
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('foo')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('{')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('function')
			->object($methodIterator = $classIterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($methodIterator->getParent())->isIdenticalTo($classIterator)
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->current())->isEqualTo('function')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo(' ')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo('bar')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo('(')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo(')')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo(' ')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo('{')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo('}')
			->boolean($methodIterator->next()->valid())->isFalse()
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('}')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->boolean($classIterator->next()->valid())->isFalse()
			->castTostring($iterator->next()->current())->isEqualTo(' ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('?>')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->boolean($iterator->next()->valid())->isFalse()
		;

		$this->startCase('Tokenizing single class with single explicit public method');

		$this->assert
			->object($tokenizer->resetIterator()->tokenize($php = '<?php class foo { public function bar() {} } ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator)->isEqualTo(21)
			->castTostring($iterator->current())->isEqualTo('<?php ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('class')
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->getParent())->isIdenticalTo($iterator)
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('foo')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('{')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('public')
			->object($methodIterator = $classIterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($methodIterator->getParent())->isIdenticalTo($classIterator)
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->current())->isEqualTo('public')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo(' ')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo('function')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo(' ')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo('bar')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo('(')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo(')')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo(' ')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo('{')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo('}')
			->boolean($methodIterator->next()->valid())->isFalse()
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('}')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->boolean($classIterator->next()->valid())->isFalse()
			->castTostring($iterator->next()->current())->isEqualTo(' ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('?>')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->boolean($iterator->next()->valid())->isFalse()
		;

		$this->startCase('Tokenizing single class with single explicit public method and one argument');

		$this->assert
			->object($tokenizer->resetIterator()->tokenize($php = '<?php class foo { public function bar($foo) {} } ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator)->isEqualTo(22)
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('class')
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->getParent())->isIdenticalTo($iterator)
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->object($classIterator = $iterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('foo')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('{')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('public')
			->object($methodIterator = $classIterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($methodIterator->getParent())->isIdenticalTo($classIterator)
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->current())->isEqualTo('public')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo(' ')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo('function')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo(' ')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo('bar')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo('(')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo('$foo')
			->object($argumentIterator = $methodIterator->getValue())->isInstanceOf('\mageekguy\atoum\php\tokenizer\iterator')
			->object($argumentIterator->getParent())->isIdenticalTo($methodIterator)
			->object($argumentIterator->current()->getParent())->isIdenticalTo($argumentIterator)
			->castTostring($argumentIterator->current())->isEqualTo('$foo')
			->boolean($argumentIterator->next()->valid())->isFalse()
			->castTostring($methodIterator->next()->current())->isEqualTo(')')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo(' ')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo('{')
			->object($methodIterator->current()->getParent())->isIdenticalTo($methodIterator)
			->castTostring($methodIterator->next()->current())->isEqualTo('}')
			->boolean($methodIterator->next()->valid())->isFalse()
			->castTostring($classIterator->next()->current())->isEqualTo(' ')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->castTostring($classIterator->next()->current())->isEqualTo('}')
			->object($classIterator->current()->getParent())->isIdenticalTo($classIterator)
			->boolean($classIterator->next()->valid())->isFalse()
			->castTostring($iterator->next()->current())->isEqualTo(' ')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->castTostring($iterator->next()->current())->isEqualTo('?>')
			->object($iterator->current()->getParent())->isIdenticalTo($iterator)
			->boolean($iterator->next()->valid())->isFalse()
		;

		$this->startCase('Tokenizing single class with single explicit public method and several arguments');

		$this->assert
			->object($tokenizer->resetIterator()->tokenize($php = '<?php class foo { public function bar($foo, $bar) {} } ?>'))->isIdenticalTo($tokenizer)
			->castToString($iterator = $tokenizer->getIterator())->isEqualTo($php)
			->sizeOf($iterator)->isEqualTo(25)
		;
	}
}

?>
