<?php

namespace mageekguy\atoum\report\fields\runner\errors;

use \mageekguy\atoum;
use \mageekguy\atoum\report;

class string extends report\fields\runner\errors
{
	const titlePrompt = '> ';
	const methodPrompt = '=> ';
	const errorPrompt = '==> ';

	public function __toString()
	{
		$string = '';

		if ($this->runner !== null)
		{
			$errors = $this->runner->getScore()->getErrors();

			$sizeOfErrors = sizeof($errors);

			if ($sizeOfErrors > 0)
			{
				$string .= self::titlePrompt . sprintf($this->locale->__('There is %d error:', 'There are %d errors:', $sizeOfErrors), $sizeOfErrors) . PHP_EOL;

				$class = null;
				$method = null;

				foreach ($errors as $error)
				{
					if ($error['class'] !== $class || $error['method'] !== $method)
					{
						$string .= self::methodPrompt . $error['class'] . '::' . $error['method'] . '():' . PHP_EOL;

						$class = $error['class'];
						$method = $error['method'];
					}

					$string .= self::errorPrompt;

					$type = self::getType($error['type']);

					switch (true)
					{
						case $error['file'] === null:
							switch (true)
							{
								case $error['errorFile'] === null:
									$string .= sprintf($this->locale->_('Error %s in unknown file on unknown line, generated by unknown file:'), $type);
									break;

								case $error['errorLine'] === null:
									$string .= sprintf($this->locale->_('Error %s in unknown file on unknown line, generated by file %s:'), $type, $error['errorFile']);
									break;

								case $error['errorLine'] !== null:
									$string .= sprintf($this->locale->_('Error %s in unknown file on unknown line, generated by file %s on line %d:'), $type, $error['errorFile'], $error['errorLine']);
									break;
							}
							break;

						case $error['line'] === null:
							switch (true)
							{
								case $error['errorFile'] === null:
									$string .= sprintf($this->locale->_('Error %s in %s on unknown line, generated by unknown file:'), $type, $error['file']);
									break;

								case $error['errorLine'] === null:
									$string .= sprintf($this->locale->_('Error %s in %s on unknown line, generated by file %s:'), $type, $error['file'], $error['errorFile']);
									break;

								case $error['errorLine'] !== null:
									$string .= sprintf($this->locale->_('Error %s in %s on unknown line, generated by file %s on line %d:'), $type, $error['file'], $error['errorFile'], $error['errorLine']);
									break;
							}
							break;

						case $error['line'] !== null:
							switch (true)
							{
								case $error['errorFile'] === null:
									$string .= sprintf($this->locale->_('Error %s in %s on line %d, generated by unknown file:'), $type, $error['file'], $error['line']);
									break;

								case $error['errorLine'] === null:
									$string .= sprintf($this->locale->_('Error %s in %s on line %d, generated by file %s:'), $type, $error['file'], $error['line'], $error['errorFile']);
									break;

								case $error['errorLine'] !== null:
									$string .= sprintf($this->locale->_('Error %s in %s on line %d, generated by file %s on line %d:'), $type, $error['file'], $error['line'], $error['errorFile'], $error['errorLine']);
									break;
							}
							break;
					}

					$string .= PHP_EOL;

					foreach (explode(PHP_EOL, $error['message']) as $line)
					{
						$string .= $line . PHP_EOL;
					}
				}
			}
		}

		return $string;
	}
}

?>
